package AdvancedSearcher::Config;

use strict;
use warnings;

sub new {
    my ($class, %args) = @_;
    my $self = {
        config_file => $args{config_file} || '/etc/advanced-searcher/config.conf',
        config => {},
        logger => $args{logger}
    };
    bless $self, $class;
    $self->load_config();
    return $self;
}

sub load_config {
    my ($self) = @_;
    
    my $config_file = $self->{config_file};
    
    unless (-e $config_file) {
        $self->{logger}->warning("Config file not found: $config_file, using defaults") if $self->{logger};
        $self->_set_defaults();
        return;
    }
    
    open my $fh, '<', $config_file or do {
        $self->{logger}->error("Cannot read config file: $!") if $self->{logger};
        $self->_set_defaults();
        return;
    };
    
    while (my $line = <$fh>) {
        chomp $line;
        
        # Skip comments and empty lines
        next if $line =~ /^\s*#/;
        next if $line =~ /^\s*$/;
        
        # Parse key=value pairs
        if ($line =~ /^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.*?)\s*$/) {
            my $key = $1;
            my $value = $2;
            
            # Remove quotes if present
            $value =~ s/^["']|["']$//g;
            
            # Convert boolean strings
            if ($value =~ /^(true|yes|1)$/i) {
                $value = 1;
            } elsif ($value =~ /^(false|no|0)$/i) {
                $value = 0;
            }
            
            $self->{config}{$key} = $value;
        }
    }
    
    close $fh;
    
    # Set defaults for any missing keys
    $self->_set_defaults();
}

sub _set_defaults {
    my ($self) = @_;
    
    my $defaults = {
        root_only => 1,
        max_results => 100,
        enable_cache => 1,
        cache_ttl => 3600,
        log_level => 'info',
        enable_debug => 0,
        check_updates => 0,
        update_check_interval => 86400,
        enable_rate_limiting => 1,
        rate_limit_per_minute => 60,
        results_per_page => 50,
        enable_autocomplete => 1,
        max_autocomplete_suggestions => 10
    };
    
    foreach my $key (keys %$defaults) {
        unless (exists $self->{config}{$key}) {
            $self->{config}{$key} = $defaults{$key};
        }
    }
}

sub get {
    my ($self, $key) = @_;
    return $self->{config}{$key};
}

sub set {
    my ($self, $key, $value) = @_;
    $self->{config}{$key} = $value;
}

sub get_all {
    my ($self) = @_;
    return {%{$self->{config}}};
}

sub save {
    my ($self) = @_;
    
    my $config_file = $self->{config_file};
    
    open my $fh, '>', $config_file or do {
        $self->{logger}->error("Cannot write config file: $!") if $self->{logger};
        return 0;
    };
    
    print $fh "# Advanced Searcher Configuration\n";
    print $fh "# Generated by Advanced Searcher\n\n";
    
    foreach my $key (sort keys %{$self->{config}}) {
        my $value = $self->{config}{$key};
        
        # Convert booleans to strings
        if ($value eq '1' || $value eq 1) {
            $value = 'true';
        } elsif ($value eq '0' || $value eq 0) {
            $value = 'false';
        }
        
        print $fh "$key=$value\n";
    }
    
    close $fh;
    
    return 1;
}

1;